# -*- coding: utf-8 -*-
"""
Django settings for testapi project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
import properties
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = getattr(properties, 'secret_key', '^z-gh3r80!o4$%6hm0zc_p6y!jpk^+nc2)q#yc5l^1(owr-!!v')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = getattr(properties, 'debug', True)

ALLOWED_HOSTS = getattr(properties, 'allowed_hosts', [])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_mongoengine',
    'tacore',
    'taapi',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'testapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'testapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': getattr(properties, "db_engine", 'django.db.backends.sqlite3'),
        'NAME': getattr(properties, "db_name", os.path.join(BASE_DIR, 'db.sqlite3')),
        'USER': getattr(properties, "db_user", None),
        'PASSWORD': getattr(properties, "db_password", ""),
        'HOST': getattr(properties, "db_host", ""),
        'PORT': getattr(properties, "db_port", ""),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = getattr(properties, "static_url", '/static/')
STATIC_ROOT = getattr(properties, "static_root", "%s/static/" % BASE_DIR)
MEDIA_URL = getattr(properties, "media_url", '/media/')
MEDIA_ROOT = getattr(properties, "media_root", "%s/media/" % BASE_DIR)

# Mongoengine
from mongoengine import connect
MONGO_DB = getattr(properties, "mongo_db", "testapi")
MONGO_HOST = getattr(properties, "mongo_host", "localhost")
MONGO_PORT = getattr(properties, "mongo_port", 27017)
MONGO_USER = getattr(properties, "mongo_user", None)
MONGO_PASSWORD = getattr(properties, "mongo_password", None)

connect(MONGO_DB, host = MONGO_HOST, port = MONGO_PORT, username = MONGO_USER, password = MONGO_PASSWORD)

# Rest framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'PAGE_SIZE': getattr(properties, "rest_page_size", 10)
}

# Cache
CACHE_VIEW_DEFAULT_TIMEOUT = getattr(properties, "cache_view_default_timeout", 60)
CACHES = {
    'default': {
        'BACKEND': getattr(properties, "cache_backend", 'django.core.cache.backends.filebased.FileBasedCache'),
        'LOCATION': getattr(properties, "cache_location", '/tmp/django_cache'),
        'TIMEOUT': CACHE_VIEW_DEFAULT_TIMEOUT
    }
}
